# Generated by Django 4.2.29 on 2026-04-14 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('device', '设备'), ('production_line', '产线'), ('area', '区域'), ('order', '订单'), ('material', '物料')], max_length=32)),
                ('source_system', models.CharField(max_length=64)),
                ('internal_code', models.CharField(max_length=128)),
                ('external_code', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['entity_type', 'source_system', 'internal_code', 'external_code'],
            },
        ),
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('opcua', 'OPCUA'), ('modbus_tcp', 'Modbus TCP'), ('sap_rfc', 'SAP RFC'), ('schedule_db', '排产数据库'), ('energy_db', '能耗数据库'), ('wms', 'WMS'), ('repair', '报修系统'), ('custom', '自定义')], max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('refresh_interval_seconds', models.PositiveIntegerField(default=300)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('connection_config', models.JSONField(blank=True, default=dict)),
                ('secret_storage_type', models.CharField(choices=[('none', '无敏感密钥'), ('env_ref', '环境变量引用'), ('encrypted', '密文存储')], default='none', max_length=16)),
                ('secret_env_mapping', models.JSONField(blank=True, default=dict)),
                ('secret_ciphertext', models.TextField(blank=True)),
                ('secret_key_version', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ScreenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen_key', models.CharField(choices=[('left', '左屏'), ('right', '右屏')], max_length=16, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('rotation_interval_seconds', models.PositiveIntegerField(default=60)),
                ('page_keys', models.JSONField(blank=True, default=list)),
                ('module_settings', models.JSONField(blank=True, default=dict)),
                ('theme_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['screen_key'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to='backoffice.area')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', '登录'), ('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除')], max_length=16)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('request_method', models.CharField(blank=True, max_length=16)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('change_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('default_status', models.CharField(choices=[('running', '运行'), ('stopped', '停机'), ('alarm', '报警'), ('offline', '离线')], default='stopped', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='backoffice.area')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='backoffice.productionline')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='codemapping',
            constraint=models.UniqueConstraint(fields=('entity_type', 'source_system', 'external_code'), name='uniq_mapping_by_external_code'),
        ),
        migrations.AddConstraint(
            model_name='codemapping',
            constraint=models.UniqueConstraint(fields=('entity_type', 'source_system', 'internal_code', 'external_code'), name='uniq_mapping_full_pair'),
        ),
        migrations.AddField(
            model_name='area',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='backoffice.area'),
        ),
    ]
