# Generated by Django 4.2.29 on 2026-04-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayContentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_key', models.CharField(max_length=32, unique=True)),
                ('company_name', models.CharField(max_length=128)),
                ('welcome_message', models.CharField(max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=255)),
                ('promo_image_urls', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['config_key'],
            },
        ),
        migrations.CreateModel(
            name='RuntimeParameterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_key', models.CharField(max_length=32, unique=True)),
                ('single_day_effective_work_hours', models.DecimalField(decimal_places=2, default=24, max_digits=5)),
                ('default_standard_capacity_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delay_warning_buffer_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gantt_window_days', models.PositiveIntegerField(default=30)),
                ('auto_scroll_enabled', models.BooleanField(default=True)),
                ('auto_scroll_rows_threshold', models.PositiveIntegerField(default=10)),
                ('recent_capacity_window_hours', models.PositiveIntegerField(default=2)),
                ('production_trend_window_hours', models.PositiveIntegerField(default=8)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['config_key'],
            },
        ),
    ]
