# Generated by Django 4.2.29 on 2026-04-14 01:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_displaycontentconfig_runtimeparameterconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_no', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='employee_no must contain only English letters and digits', regex='^[A-Za-z0-9]+$')])),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('employee', '员工'), ('team_leader', '班组长'), ('supervisor', '主管')], default='employee', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['employee_no'],
            },
        ),
    ]
