# Generated by Django 5.2.13 on 2026-04-27 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0007_datasourcehealthsnapshot_devicestatussnapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasourceconfig",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("opcua", "OPCUA"),
                    ("modbus_tcp", "Modbus TCP"),
                    ("sap_rfc", "SAP RFC"),
                    ("schedule_db", "排产数据库"),
                    ("energy_db", "能耗数据库"),
                    ("wms", "WMS数据库"),
                    ("repair", "报修系统"),
                    ("custom", "自定义"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="OpcUaHistorySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.CharField(max_length=255)),
                ("value", models.TextField(blank=True, default="")),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("uncertain", "Uncertain"),
                            ("bad", "Bad"),
                        ],
                        default="good",
                        max_length=16,
                    ),
                ),
                ("sampled_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opcua_history_samples",
                        to="backoffice.datasourceconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-sampled_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["data_source", "-sampled_at"],
                        name="opcua_hist_ds_time_idx",
                    )
                ],
            },
        ),
    ]
