# Generated by Django 5.2.13 on 2026-04-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0008_alter_datasourceconfig_source_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasourceconfig",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("opcua", "OPCUA"),
                    ("modbus_tcp", "Modbus TCP"),
                    ("sap_rfc", "SAP RFC"),
                    ("database", "数据库"),
                    ("schedule_db", "排产数据库"),
                    ("energy_db", "能耗数据库"),
                    ("wms", "WMS数据库"),
                    ("repair", "报修系统"),
                    ("custom", "自定义"),
                ],
                max_length=32,
            ),
        ),
    ]
