# Generated by Django 5.2.13 on 2026-05-09 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_merge_database_source_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenpagebinding',
            options={'ordering': ['screen_key', 'page_key']},
        ),
    ]
