# Generated by Django 5.2.12 on 2026-05-10 00:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0025_energy_catalog_and_screen_binding_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={
                "ordering": ["code"],
                "verbose_name": "区域",
                "verbose_name_plural": "区域",
            },
        ),
        migrations.AlterModelOptions(
            name="codemapping",
            options={
                "ordering": [
                    "entity_type",
                    "source_system",
                    "internal_code",
                    "external_code",
                ],
                "verbose_name": "编码映射",
                "verbose_name_plural": "编码映射",
            },
        ),
        migrations.AlterModelOptions(
            name="datasourceconfig",
            options={
                "ordering": ["code"],
                "verbose_name": "数据源配置",
                "verbose_name_plural": "数据源配置",
            },
        ),
        migrations.AlterModelOptions(
            name="datasourcedevicebinding",
            options={
                "ordering": ["data_source_id", "device_id"],
                "verbose_name": "数据源-设备绑定",
                "verbose_name_plural": "数据源-设备绑定",
            },
        ),
        migrations.AlterModelOptions(
            name="datasourcehealthsnapshot",
            options={
                "ordering": ["source_key"],
                "verbose_name": "数据源健康快照",
                "verbose_name_plural": "数据源健康快照",
            },
        ),
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["code"],
                "verbose_name": "设备",
                "verbose_name_plural": "设备",
            },
        ),
        migrations.AlterModelOptions(
            name="devicestatussnapshot",
            options={
                "ordering": ["snapshot_key"],
                "verbose_name": "设备状态快照",
                "verbose_name_plural": "设备状态快照",
            },
        ),
        migrations.AlterModelOptions(
            name="displaycontentconfig",
            options={
                "ordering": ["config_key"],
                "verbose_name": "大屏展示内容配置",
                "verbose_name_plural": "大屏展示内容配置",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["employee_no"],
                "verbose_name": "员工",
                "verbose_name_plural": "员工",
            },
        ),
        migrations.AlterModelOptions(
            name="energydashboardsnapshot",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "能耗看板快照缓存",
                "verbose_name_plural": "能耗看板快照缓存",
            },
        ),
        migrations.AlterModelOptions(
            name="energyequipmentcatalog",
            options={
                "ordering": ["display_name", "equipment_id"],
                "verbose_name": "能耗设备目录",
                "verbose_name_plural": "能耗设备目录",
            },
        ),
        migrations.AlterModelOptions(
            name="energysnapshot",
            options={
                "ordering": ["snapshot_key"],
                "verbose_name": "能耗快照",
                "verbose_name_plural": "能耗快照",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["code"],
                "verbose_name": "物料",
                "verbose_name_plural": "物料",
            },
        ),
        migrations.AlterModelOptions(
            name="opcuahistorysample",
            options={
                "ordering": ["-sampled_at", "-id"],
                "verbose_name": "OPC UA 历史采样",
                "verbose_name_plural": "OPC UA 历史采样",
            },
        ),
        migrations.AlterModelOptions(
            name="operationlog",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at", "order_no"],
                "verbose_name": "生产订单",
                "verbose_name_plural": "生产订单",
            },
        ),
        migrations.AlterModelOptions(
            name="pagemoduleswitch",
            options={
                "ordering": ["screen_key", "sort_order", "module_key"],
                "verbose_name": "页面模块开关",
                "verbose_name_plural": "页面模块开关",
            },
        ),
        migrations.AlterModelOptions(
            name="productionline",
            options={
                "ordering": ["code"],
                "verbose_name": "产线",
                "verbose_name_plural": "产线",
            },
        ),
        migrations.AlterModelOptions(
            name="productionsnapshot",
            options={
                "ordering": ["snapshot_key"],
                "verbose_name": "产量快照",
                "verbose_name_plural": "产量快照",
            },
        ),
        migrations.AlterModelOptions(
            name="runtimeparameterconfig",
            options={
                "ordering": ["config_key"],
                "verbose_name": "运行时参数配置",
                "verbose_name_plural": "运行时参数配置",
            },
        ),
        migrations.AlterModelOptions(
            name="schedulesnapshot",
            options={
                "ordering": ["snapshot_key"],
                "verbose_name": "排产快照",
                "verbose_name_plural": "排产快照",
            },
        ),
        migrations.AlterModelOptions(
            name="screenconfig",
            options={
                "ordering": ["area__code", "screen_key"],
                "verbose_name": "大屏屏幕配置",
                "verbose_name_plural": "大屏屏幕配置",
            },
        ),
        migrations.AlterModelOptions(
            name="screenpagebinding",
            options={
                "ordering": ["area_id", "screen_key", "page_key"],
                "verbose_name": "大屏子页数据源绑定",
                "verbose_name_plural": "大屏子页数据源绑定",
            },
        ),
        migrations.AlterField(
            model_name="area",
            name="code",
            field=models.CharField(
                help_text="业务唯一编码",
                max_length=64,
                unique=True,
                verbose_name="区域编码",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="area",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=128, verbose_name="区域名称"),
        ),
        migrations.AlterField(
            model_name="area",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="area",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="backoffice.area",
                verbose_name="上级区域",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("device", "设备"),
                    ("production_line", "产线"),
                    ("area", "区域"),
                    ("order", "订单"),
                    ("material", "物料"),
                ],
                max_length=32,
                verbose_name="实体类型",
            ),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="external_code",
            field=models.CharField(max_length=128, verbose_name="外部系统编码"),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="internal_code",
            field=models.CharField(max_length=128, verbose_name="本系统编码"),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="source_system",
            field=models.CharField(
                help_text="如 sap、energy 等标识",
                max_length=64,
                verbose_name="外部来源系统",
            ),
        ),
        migrations.AlterField(
            model_name="codemapping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="code",
            field=models.CharField(
                max_length=64, unique=True, verbose_name="数据源编码"
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="connection_config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="连接参数（JSON，非密钥部分）"
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="devices",
            field=models.ManyToManyField(
                blank=True,
                related_name="data_sources",
                through="backoffice.DataSourceDeviceBinding",
                to="backoffice.device",
                verbose_name="关联设备",
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="name",
            field=models.CharField(max_length=128, verbose_name="数据源名称"),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="node",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="节点/点表配置（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="refresh_interval_seconds",
            field=models.PositiveIntegerField(
                default=300, verbose_name="刷新间隔（秒）"
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="secret_ciphertext",
            field=models.TextField(blank=True, verbose_name="密文载荷"),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="secret_env_mapping",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="环境变量映射（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="secret_key_version",
            field=models.CharField(blank=True, max_length=32, verbose_name="密钥版本"),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="secret_storage_type",
            field=models.CharField(
                choices=[
                    ("none", "无敏感密钥"),
                    ("env_ref", "环境变量引用"),
                    ("encrypted", "密文存储"),
                ],
                default="none",
                max_length=16,
                verbose_name="密钥存储方式",
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("opcua", "OPCUA"),
                    ("modbus_tcp", "Modbus TCP"),
                    ("sap_rfc", "SAP RFC"),
                    ("database", "数据库"),
                    ("repair", "报修系统"),
                    ("custom", "自定义"),
                ],
                max_length=32,
                verbose_name="数据源类型",
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="timeout_seconds",
            field=models.PositiveIntegerField(
                default=30, verbose_name="请求超时（秒）"
            ),
        ),
        migrations.AlterField(
            model_name="datasourceconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="datasourcedevicebinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="datasourcedevicebinding",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_bindings",
                to="backoffice.datasourceconfig",
                verbose_name="数据源配置",
            ),
        ),
        migrations.AlterField(
            model_name="datasourcedevicebinding",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_source_bindings",
                to="backoffice.device",
                verbose_name="设备",
            ),
        ),
        migrations.AlterField(
            model_name="datasourcedevicebinding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="details",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="扩展详情（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="display_name",
            field=models.CharField(max_length=128, verbose_name="展示名称"),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="error_message",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="最近错误摘要"
            ),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="fallback_in_use",
            field=models.BooleanField(default=False, verbose_name="是否使用兜底数据"),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="is_stale",
            field=models.BooleanField(default=False, verbose_name="数据是否过期"),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="last_attempt_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近尝试时间"
            ),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="last_success_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最近成功时间"
            ),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="source_key",
            field=models.CharField(
                help_text="与采集任务约定一致",
                max_length=32,
                unique=True,
                verbose_name="数据源键",
            ),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="status",
            field=models.CharField(
                choices=[("healthy", "healthy"), ("failed", "failed")],
                default="healthy",
                max_length=16,
                verbose_name="健康状态",
            ),
        ),
        migrations.AlterField(
            model_name="datasourcehealthsnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="device",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="backoffice.area",
                verbose_name="所属区域",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="code",
            field=models.CharField(
                help_text="业务唯一编码",
                max_length=64,
                unique=True,
                verbose_name="设备编码",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="device",
            name="default_status",
            field=models.CharField(
                choices=[
                    ("running", "运行"),
                    ("stopped", "停机"),
                    ("alarm", "报警"),
                    ("offline", "离线"),
                ],
                default="stopped",
                help_text="运行/停机/报警/离线，用于展示兜底",
                max_length=16,
                verbose_name="默认状态",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="ip",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="设备 IP"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=128, verbose_name="设备名称"),
        ),
        migrations.AlterField(
            model_name="device",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="device",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                help_text="保存时会尝试同步区域的归属区域",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to="backoffice.productionline",
                verbose_name="所属产线",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="abnormal_count",
            field=models.PositiveIntegerField(default=0, verbose_name="异常台数"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="generated_at",
            field=models.DateTimeField(verbose_name="快照生成时间"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="last_success_at",
            field=models.DateTimeField(verbose_name="最近成功写入时间"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="running_count",
            field=models.PositiveIntegerField(default=0, verbose_name="运行台数"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="snapshot_key",
            field=models.CharField(
                help_text="区分不同数据源或视图",
                max_length=32,
                unique=True,
                verbose_name="快照键",
            ),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="source_updated_at",
            field=models.DateTimeField(verbose_name="源数据时间"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="status_breakdown",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="状态分布（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="total_count",
            field=models.PositiveIntegerField(default=0, verbose_name="设备总数"),
        ),
        migrations.AlterField(
            model_name="devicestatussnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="company_name",
            field=models.CharField(max_length=128, verbose_name="企业/厂区名称"),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="config_key",
            field=models.CharField(
                help_text="区分多套展示方案",
                max_length=32,
                unique=True,
                verbose_name="配置键",
            ),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="logo_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Logo 地址"
            ),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="promo_image_urls",
            field=models.JSONField(
                blank=True, default=list, verbose_name="宣传图片 URL 列表（JSON 数组）"
            ),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="displaycontentconfig",
            name="welcome_message",
            field=models.CharField(max_length=255, verbose_name="欢迎语"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_no",
            field=models.CharField(
                help_text="仅英文字母与数字",
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="employee_no must contain only English letters and digits",
                        regex="^[A-Za-z0-9]+$",
                    )
                ],
                verbose_name="员工号",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=128, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "员工"),
                    ("team_leader", "班组长"),
                    ("supervisor", "主管"),
                ],
                default="employee",
                max_length=16,
                verbose_name="角色",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="energydashboardsnapshot",
            name="cache_key",
            field=models.CharField(
                db_index=True,
                help_text="区分请求维度",
                max_length=64,
                unique=True,
                verbose_name="缓存键",
            ),
        ),
        migrations.AlterField(
            model_name="energydashboardsnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="energydashboardsnapshot",
            name="data_source_ids",
            field=models.JSONField(default=list, verbose_name="关联数据源 ID 列表"),
        ),
        migrations.AlterField(
            model_name="energydashboardsnapshot",
            name="filters",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="筛选条件（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="energydashboardsnapshot",
            name="refresh_scope",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="刷新范围标识"
            ),
        ),
        migrations.AlterField(
            model_name="energydashboardsnapshot",
            name="snapshot_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="聚合结果载荷（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="energydashboardsnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="energyequipmentcatalog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="energyequipmentcatalog",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="energy_equipment_catalog",
                to="backoffice.datasourceconfig",
                verbose_name="数据来源配置",
            ),
        ),
        migrations.AlterField(
            model_name="energyequipmentcatalog",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="展示名称"
            ),
        ),
        migrations.AlterField(
            model_name="energyequipmentcatalog",
            name="equipment_id",
            field=models.CharField(
                db_index=True, max_length=64, verbose_name="外部设备/表计 ID"
            ),
        ),
        migrations.AlterField(
            model_name="energyequipmentcatalog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="area_summaries",
            field=models.JSONField(
                blank=True, default=list, verbose_name="按区域汇总（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="generated_at",
            field=models.DateTimeField(verbose_name="快照生成时间"),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="last_success_at",
            field=models.DateTimeField(verbose_name="最近成功写入时间"),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="snapshot_key",
            field=models.CharField(max_length=32, unique=True, verbose_name="快照键"),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="source_updated_at",
            field=models.DateTimeField(verbose_name="源数据时间"),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="total_consumption",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="总能耗"
            ),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="unit",
            field=models.CharField(
                default="kWh", max_length=16, verbose_name="能耗单位"
            ),
        ),
        migrations.AlterField(
            model_name="energysnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="material",
            name="code",
            field=models.CharField(max_length=64, unique=True, verbose_name="物料编码"),
        ),
        migrations.AlterField(
            model_name="material",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="material",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="material",
            name="name",
            field=models.CharField(max_length=128, verbose_name="物料名称"),
        ),
        migrations.AlterField(
            model_name="material",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="material",
            name="specification",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="规格型号"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="计量单位"
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="opcuahistorysample",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
        ),
        migrations.AlterField(
            model_name="opcuahistorysample",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opcua_history_samples",
                to="backoffice.datasourceconfig",
                verbose_name="数据源配置",
            ),
        ),
        migrations.AlterField(
            model_name="opcuahistorysample",
            name="node_id",
            field=models.CharField(max_length=255, verbose_name="OPC UA NodeId"),
        ),
        migrations.AlterField(
            model_name="opcuahistorysample",
            name="quality",
            field=models.CharField(
                choices=[("good", "Good"), ("uncertain", "Uncertain"), ("bad", "Bad")],
                default="good",
                max_length=16,
                verbose_name="数据质量",
            ),
        ),
        migrations.AlterField(
            model_name="opcuahistorysample",
            name="sampled_at",
            field=models.DateTimeField(verbose_name="采样时间（业务时间）"),
        ),
        migrations.AlterField(
            model_name="opcuahistorysample",
            name="value",
            field=models.TextField(
                blank=True, default="", verbose_name="采样值（文本）"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "登录"),
                    ("CREATE", "创建"),
                    ("UPDATE", "更新"),
                    ("DELETE", "删除"),
                ],
                max_length=16,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作人",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="change_summary",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="变更摘要（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="request_method",
            field=models.CharField(blank=True, max_length=16, verbose_name="HTTP 方法"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="request_path",
            field=models.CharField(blank=True, max_length=255, verbose_name="请求路径"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="target_id",
            field=models.CharField(blank=True, max_length=64, verbose_name="目标主键"),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="target_label",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="目标可读标签"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="target_type",
            field=models.CharField(
                help_text="如模型名或业务对象分类",
                max_length=64,
                verbose_name="目标类型",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="actual_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="实际结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="actual_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="实际开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="完成数量"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="order",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="backoffice.material",
                verbose_name="物料",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_no",
            field=models.CharField(max_length=64, unique=True, verbose_name="订单号"),
        ),
        migrations.AlterField(
            model_name="order",
            name="planned_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="计划结束时间"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="planned_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="计划开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="production_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="backoffice.productionline",
                verbose_name="产线",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=14, verbose_name="计划数量"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "计划"),
                    ("in_progress", "生产中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                ],
                default="planned",
                max_length=16,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="unit",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="数量单位"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="label",
            field=models.CharField(max_length=128, verbose_name="模块显示名称"),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="module_key",
            field=models.CharField(
                help_text="与前端约定一致", max_length=64, verbose_name="模块键"
            ),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="screen_key",
            field=models.CharField(
                choices=[("left", "左屏"), ("right", "右屏")],
                max_length=16,
                verbose_name="屏幕侧",
            ),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="排序权重"),
        ),
        migrations.AlterField(
            model_name="pagemoduleswitch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_lines",
                to="backoffice.area",
                verbose_name="所属区域",
            ),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="code",
            field=models.CharField(
                help_text="业务唯一编码",
                max_length=64,
                unique=True,
                verbose_name="产线编码",
            ),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="name",
            field=models.CharField(max_length=128, verbose_name="产线名称"),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="productionline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="generated_at",
            field=models.DateTimeField(verbose_name="快照生成时间"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="last_success_at",
            field=models.DateTimeField(verbose_name="最近成功写入时间"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="line_summaries",
            field=models.JSONField(
                blank=True, default=list, verbose_name="按产线汇总（JSON 数组）"
            ),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="overall_completion_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="总体完成率（%）",
            ),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="snapshot_key",
            field=models.CharField(max_length=32, unique=True, verbose_name="快照键"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="source_updated_at",
            field=models.DateTimeField(verbose_name="源数据时间"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="total_produced_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="总完成产量"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="total_target_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="总目标产量"),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="trend_points",
            field=models.JSONField(
                blank=True, default=list, verbose_name="趋势点（JSON 数组）"
            ),
        ),
        migrations.AlterField(
            model_name="productionsnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="auto_scroll_enabled",
            field=models.BooleanField(
                default=True, verbose_name="是否启用列表自动滚动"
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="auto_scroll_rows_threshold",
            field=models.PositiveIntegerField(
                default=10, verbose_name="超过该行数触发自动滚动"
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="config_key",
            field=models.CharField(max_length=32, unique=True, verbose_name="配置键"),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="default_standard_capacity_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="默认标准产能（每小时）",
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="delay_warning_buffer_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="延期预警缓冲（小时）",
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="gantt_window_days",
            field=models.PositiveIntegerField(
                default=30, verbose_name="甘特图展示窗口（天）"
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="production_trend_window_hours",
            field=models.PositiveIntegerField(
                default=8, verbose_name="产量趋势统计窗口（小时）"
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="recent_capacity_window_hours",
            field=models.PositiveIntegerField(
                default=2, verbose_name="近期产能统计窗口（小时）"
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="single_day_effective_work_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=24,
                help_text="用于延期预测等计算",
                max_digits=5,
                verbose_name="单日有效工时（小时）",
            ),
        ),
        migrations.AlterField(
            model_name="runtimeparameterconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="generated_at",
            field=models.DateTimeField(verbose_name="快照生成时间"),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="last_success_at",
            field=models.DateTimeField(verbose_name="最近成功写入时间"),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="legend_items",
            field=models.JSONField(
                blank=True, default=list, verbose_name="图例项（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="line_schedules",
            field=models.JSONField(
                blank=True, default=list, verbose_name="按产线排产数据（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="risk_summary",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="风险摘要（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="snapshot_key",
            field=models.CharField(max_length=32, unique=True, verbose_name="快照键"),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="source_updated_at",
            field=models.DateTimeField(verbose_name="源数据时间"),
        ),
        migrations.AlterField(
            model_name="schedulesnapshot",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="按区域区分左右屏布局；空值表示兼容旧数据的兜底配置",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="screen_configs",
                to="backoffice.area",
                verbose_name="所属区域",
            ),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="module_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="模块开关与参数（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="page_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='子页面键列表，如 ["overview", "realtime"]；空列表使用默认顺序',
                verbose_name="子页面轮播顺序",
            ),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="rotation_interval_seconds",
            field=models.PositiveIntegerField(
                default=60, verbose_name="子页面轮播间隔（秒）"
            ),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="screen_key",
            field=models.CharField(
                choices=[("left", "左屏"), ("right", "右屏")],
                help_text="left/right",
                max_length=16,
                verbose_name="屏幕侧",
            ),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, verbose_name="副标题"),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="theme_settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="主题配置（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="title",
            field=models.CharField(max_length=128, verbose_name="大屏标题"),
        ),
        migrations.AlterField(
            model_name="screenconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="空表示全局兜底绑定",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="screen_page_bindings",
                to="backoffice.area",
                verbose_name="所属区域",
            ),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="binding_source_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="与 DataSourceConfig.source_type 对齐；先选类型再选具体数据源",
                max_length=32,
                verbose_name="绑定数据源类型",
            ),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="data_source_ids",
            field=models.JSONField(
                blank=True, default=list, verbose_name="绑定的数据源 ID 列表（JSON）"
            ),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="energy_equipment_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="platform_equipment.e_id，用于能耗页筛选",
                verbose_name="能耗设备 ID 列表（JSON）",
            ),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="notes",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="page_key",
            field=models.CharField(
                help_text="与前端路由/组件约定一致",
                max_length=64,
                verbose_name="子页面键",
            ),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="screen_key",
            field=models.CharField(
                choices=[("left", "左屏"), ("right", "右屏")],
                max_length=16,
                verbose_name="屏幕侧",
            ),
        ),
        migrations.AlterField(
            model_name="screenpagebinding",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
