# Generated by Django 5.2.12 on 2026-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backoffice", "0027_db_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="runtimeparameterconfig",
            name="gantt_anchor_mode",
            field=models.CharField(
                choices=[
                    ("earliest_order", "最早未完成工单"),
                    ("current_time", "当前日期"),
                ],
                db_comment="甘特窗口锚点模式 earliest_order / current_time",
                default="earliest_order",
                help_text="当前日期：从今日起向后覆盖窗口天数；最早未完成工单：从区域内最早一笔工单计划开始日起计。",
                max_length=32,
                verbose_name="甘特图开始时间",
            ),
        ),
    ]
