# Generated by Django 5.2.13 on 2026-06-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0031_screenpagebinding_device_ids'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='opcuahistorysample',
            table_comment='OPC UA 读点历史',
        ),
        migrations.AlterField(
            model_name='opcuahistorysample',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='行插入时间', verbose_name='记录入库时间'),
        ),
    ]
