import { RESERVED_FIELDS } from "./shared.js";
import {
  ACTIVE_STATUS_OPTIONS,
  DEVICE_STATUS_OPTIONS,
  EMPLOYEE_ROLE_OPTIONS,
  ORDER_STATUS_OPTIONS,
} from "./options.js";

export const ledgerResourceDefinitions = {
areas: {
    label: "区域台账",
    endpoint: "/api/admin/areas",
    itemLabel: "区域",
    useModalForm: true,
    columns: [
      { key: "code", label: "编码" },
      { key: "name", label: "名称" },
      { key: "parentName", label: "上级区域" },
      { key: "isActive", label: "启用" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "编码/名称/备注" },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "parent_id", label: "上级区域", type: "resourceSelect", resource: "areas", allowBlank: true },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      { key: "code", label: "编码", type: "text", required: true, defaultValue: "" },
      { key: "name", label: "名称", type: "text", required: true, defaultValue: "" },
      { key: "parentId", label: "上级区域", type: "resourceSelect", resource: "areas", allowBlank: true, defaultValue: "" },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  productionLines: {
    label: "产线台账",
    endpoint: "/api/admin/production-lines",
    itemLabel: "产线",
    useModalForm: true,
    columns: [
      { key: "code", label: "编码" },
      { key: "name", label: "名称" },
      { key: "areaName", label: "所属区域" },
      { key: "isActive", label: "启用" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "编码/名称/区域/备注" },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "area_id", label: "所属区域", type: "resourceSelect", resource: "areas", allowBlank: true },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      { key: "code", label: "编码", type: "text", required: true, defaultValue: "" },
      { key: "name", label: "名称", type: "text", required: true, defaultValue: "" },
      { key: "areaId", label: "所属区域", type: "resourceSelect", resource: "areas", allowBlank: true, defaultValue: "" },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  devices: {
    label: "设备台账",
    endpoint: "/api/admin/devices",
    itemLabel: "设备",
    useModalForm: true,
    columns: [
      { key: "code", label: "编码" },
      { key: "name", label: "名称" },
      { key: "ip", label: "IP" },
      { key: "areaName", label: "区域" },
      { key: "productionLineName", label: "产线" },
      { key: "defaultStatus", label: "状态", options: DEVICE_STATUS_OPTIONS },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "编码/名称/IP/区域/产线" },
      { key: "default_status", label: "状态", type: "select", options: DEVICE_STATUS_OPTIONS },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "area_id", label: "区域", type: "resourceSelect", resource: "areas", allowBlank: true },
      { key: "production_line_id", label: "产线", type: "resourceSelect", resource: "productionLines", allowBlank: true },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      { key: "code", label: "编码", type: "text", required: true, defaultValue: "" },
      { key: "name", label: "名称", type: "text", required: true, defaultValue: "" },
      { key: "ip", label: "设备IP", type: "text", defaultValue: "" },
      { key: "areaId", label: "所属区域", type: "resourceSelect", resource: "areas", allowBlank: true, defaultValue: "" },
      { key: "productionLineId", label: "所属产线", type: "resourceSelect", resource: "productionLines", allowBlank: true, defaultValue: "" },
      {
        key: "defaultStatus",
        label: "状态",
        type: "select",
        required: true,
        defaultValue: "stopped",
        options: DEVICE_STATUS_OPTIONS,
      },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  employees: {
    label: "员工台账",
    endpoint: "/api/admin/employees",
    itemLabel: "员工",
    useModalForm: true,
    columns: [
      { key: "employeeNo", label: "员工号" },
      { key: "name", label: "姓名" },
      { key: "roleLabel", label: "角色" },
      { key: "isActive", label: "启用" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "工号/姓名/备注" },
      { key: "role", label: "角色", type: "select", options: EMPLOYEE_ROLE_OPTIONS },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      { key: "employeeNo", label: "员工号", type: "text", required: true, defaultValue: "" },
      { key: "name", label: "姓名", type: "text", required: true, defaultValue: "" },
      {
        key: "role",
        label: "角色",
        type: "select",
        required: true,
        defaultValue: "employee",
        options: EMPLOYEE_ROLE_OPTIONS,
      },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  materials: {
    label: "物料台账",
    endpoint: "/api/admin/materials",
    itemLabel: "物料",
    useModalForm: true,
    columns: [
      { key: "code", label: "编码" },
      { key: "name", label: "名称" },
      { key: "specification", label: "规格" },
      { key: "unit", label: "单位" },
      { key: "isActive", label: "启用" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "编码/名称/规格/备注" },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      { key: "code", label: "编码", type: "text", required: true, defaultValue: "" },
      { key: "name", label: "名称", type: "text", required: true, defaultValue: "" },
      { key: "specification", label: "规格", type: "text", defaultValue: "" },
      { key: "unit", label: "单位", type: "text", defaultValue: "" },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  orders: {
    label: "订单台账",
    endpoint: "/api/admin/orders",
    itemLabel: "订单",
    useModalForm: true,
    columns: [
      { key: "orderNo", label: "订单号" },
      { key: "materialName", label: "物料" },
      { key: "productionLineName", label: "产线" },
      { key: "quantity", label: "计划数量" },
      { key: "completedQuantity", label: "完成数量" },
      { key: "statusLabel", label: "状态" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "订单号/物料/产线/备注" },
      { key: "status", label: "状态", type: "select", options: ORDER_STATUS_OPTIONS },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "material_id", label: "物料", type: "resourceSelect", resource: "materials", allowBlank: true },
      { key: "production_line_id", label: "产线", type: "resourceSelect", resource: "productionLines", allowBlank: true },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      { key: "orderNo", label: "订单号", type: "text", required: true, defaultValue: "" },
      { key: "materialId", label: "物料", type: "resourceSelect", resource: "materials", allowBlank: true, defaultValue: "" },
      { key: "productionLineId", label: "产线", type: "resourceSelect", resource: "productionLines", allowBlank: true, defaultValue: "" },
      { key: "quantity", label: "计划数量", type: "decimal", required: true, defaultValue: "0.00" },
      { key: "completedQuantity", label: "完成数量", type: "decimal", defaultValue: "0.00" },
      { key: "unit", label: "单位", type: "text", defaultValue: "" },
      {
        key: "status",
        label: "状态",
        type: "select",
        required: true,
        defaultValue: "planned",
        options: ORDER_STATUS_OPTIONS,
      },
      { key: "plannedStart", label: "计划开始", type: "text", defaultValue: "", placeholder: "YYYY-MM-DD HH:MM:SS" },
      { key: "plannedEnd", label: "计划结束", type: "text", defaultValue: "", placeholder: "YYYY-MM-DD HH:MM:SS" },
      { key: "actualStart", label: "实际开始", type: "text", defaultValue: "", placeholder: "YYYY-MM-DD HH:MM:SS" },
      { key: "actualEnd", label: "实际结束", type: "text", defaultValue: "", placeholder: "YYYY-MM-DD HH:MM:SS" },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
};
