import { RESERVED_FIELDS } from "./shared.js";
import {
  ACTIVE_STATUS_OPTIONS,
  DATA_SOURCE_BINDING_CATEGORY_OPTIONS,
  REALTIME_LAYOUT_OPTIONS,
  SCREEN_KEY_OPTIONS,
  SCREEN_PAGE_KEY_FLAT_OPTIONS,
} from "./options.js";

export const screenResourceDefinitions = {
  screenConfigs: {
    label: "左右屏配置",
    endpoint: "/api/admin/screen-configs",
    itemLabel: "屏幕配置",
    useModalForm: true,
    wideModal: true,
    bulkApplyToolbar: {
      apiPath: "bulk-rotation-interval",
      valueKey: "rotationIntervalSeconds",
      label: "轮播时长（秒）",
      defaultInput: "60",
      min: 5,
      max: 86400,
      successMessage: (count, seconds) => `已更新 ${count} 条屏幕配置的轮播时长为 ${seconds} 秒。`,
      errorFallback: "批量设置轮播时长失败，请稍后重试。",
    },
    relatedResources: ["screenPageBindings"],
    columns: [
      { key: "areaName", label: "区域" },
      { key: "screenKey", label: "屏幕" },
      { key: "title", label: "标题" },
      { key: "rotationIntervalSeconds", label: "轮播时长（秒）" },
      { key: "isActive", label: "启用" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "屏幕键/标题/副标题" },
      { key: "area_id", label: "区域", type: "resourceSelect", resource: "areas", allowBlank: true },
      { key: "screen_key", label: "屏幕", type: "select", options: SCREEN_KEY_OPTIONS },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
    ],
    fields: [
      { key: "areaId", label: "区域", type: "resourceSelect", resource: "areas", allowBlank: false, defaultValue: "" },
      {
        key: "screenKey",
        label: "屏幕",
        type: "select",
        required: true,
        defaultValue: "left",
        options: SCREEN_KEY_OPTIONS,
      },
      { key: "title", label: "标题", type: "text", required: true, defaultValue: "" },
      { key: "subtitle", label: "副标题", type: "text", defaultValue: "" },
      { key: "rotationIntervalSeconds", label: "轮播时长（秒）", type: "integer", required: true, defaultValue: 60 },
      {
        key: "pageOrder",
        label: "轮播子页面顺序",
        type: "screenPageTransfer",
        screenKeyField: "screenKey",
        areaIdField: "areaId",
        defaultValue: [],
      },
      { key: "moduleSettings", label: "模块开关", type: "json", defaultValue: {} },
      { key: "themeSettings", label: "主题配置", type: "json", defaultValue: {} },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      ...RESERVED_FIELDS,
    ],
  },
  dataSourceConfigs: {
    label: "数据源列表",
    endpoint: "/api/admin/data-source-configs",
    itemLabel: "数据源",
    useModalForm: true,
    columns: [
      { key: "code", label: "编码" },
      { key: "name", label: "名称" },
      { key: "sourceType", label: "类型" },
    ],
    queryFields: [],
    fields: [
      { key: "code", label: "编码", type: "text", required: true, defaultValue: "" },
      { key: "name", label: "名称", type: "text", required: true, defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  screenPageBindings: {
    label: "屏幕子页面",
    endpoint: "/api/admin/screen-page-bindings",
    itemLabel: "子页面",
    useModalForm: true,
    bulkApplyToolbar: {
      apiPath: "bulk-set-enabled",
      inputKind: "booleanSelect",
      valueKey: "isEnabled",
      label: "启用",
      defaultInput: "true",
      selectOptions: [
        { value: "true", label: "启用" },
        { value: "false", label: "停用" },
      ],
      successMessage: (count, enabled) =>
        `已批量更新 ${count} 条子页面绑定为「${enabled ? "启用" : "停用"}」。`,
      errorFallback: "批量设置启用状态失败，请稍后重试。",
    },
    columns: [
      { key: "bindingScopeLabel", label: "屏幕（区域）" },
      { key: "pageKeyLabel", label: "子页面" },
      { key: "bindingSourceType", label: "数据源类型", options: DATA_SOURCE_BINDING_CATEGORY_OPTIONS },
      { key: "dataSourceIds", label: "数据源", cellFormat: "idCount" },
      { key: "realtimeLayout", label: "实时监控模板", options: REALTIME_LAYOUT_OPTIONS, showWhenPageKey: "realtime" },
      { key: "realtimeDemoMode", label: "展示模式", showWhenPageKey: "realtime" },
      { key: "energyEquipmentIds", label: "能耗表计", cellFormat: "idCount" },
      { key: "isEnabled", label: "启用" },
    ],
    queryFields: [
      { key: "area_id", label: "区域", type: "resourceSelect", resource: "areas", allowBlank: true },
      { key: "screen_key", label: "屏幕", type: "select", options: SCREEN_KEY_OPTIONS },
      { key: "is_enabled", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
    ],
    fields: [
      {
        key: "areaId",
        label: "所属区域",
        type: "resourceSelect",
        resource: "areas",
        allowBlank: false,
        required: true,
        defaultValue: "",
      },
      {
        key: "pageKey",
        label: "子页面",
        type: "select",
        required: true,
        defaultValue: "overview",
        options: SCREEN_PAGE_KEY_FLAT_OPTIONS,
      },
      {
        key: "screenKey",
        label: "左/右屏",
        type: "select",
        required: true,
        defaultValue: "left",
        options: SCREEN_KEY_OPTIONS,
      },
      {
        key: "bindingSourceType",
        label: "数据源类型",
        type: "select",
        defaultValue: "",
        options: DATA_SOURCE_BINDING_CATEGORY_OPTIONS,
      },
      {
        key: "dataSourceIds",
        label: "数据源（按类型筛选，可多选）",
        type: "resourceMultiSelectFiltered",
        resource: "dataSourceConfigs",
        filterByField: "bindingSourceType",
        filterOptionKey: "sourceType",
        defaultValue: [],
      },
      {
        key: "realtimeLayout",
        label: "实时监控模板",
        type: "select",
        defaultValue: "",
        options: REALTIME_LAYOUT_OPTIONS,
        visibleWhen: { field: "pageKey", value: "realtime" },
      },
      {
        key: "realtimeDemoMode",
        label: "展示模式（全部在线演示数据）",
        type: "checkbox",
        defaultValue: true,
        visibleWhen: { field: "pageKey", value: "realtime" },
      },
      {
        key: "deviceIds",
        label: "监控设备（可选，决定卡片标题）",
        type: "resourceMultiSelectFiltered",
        resource: "devices",
        filterByField: "areaId",
        filterOptionKey: "areaId",
        defaultValue: [],
        visibleWhen: { field: "pageKey", value: "realtime" },
      },
      {
        key: "energyEquipmentIds",
        label: "能耗表计（platform_equipment / p_e_name）",
        type: "energyDatabaseEquipmentMulti",
        dataSourceField: "dataSourceIds",
        defaultValue: [],
        visibleWhen: { field: "pageKey", value: "energy" },
      },
      { key: "isEnabled", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  pageModuleSwitches: {
    label: "页面模块开关",
    endpoint: "/api/admin/page-module-switches",
    itemLabel: "模块开关",
    useModalForm: true,
    columns: [
      { key: "screenKey", label: "屏幕", options: SCREEN_KEY_OPTIONS },
      { key: "moduleKey", label: "模块标识" },
      { key: "label", label: "模块名称" },
      { key: "sortOrder", label: "排序" },
      { key: "isEnabled", label: "启用" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "模块标识/名称/备注" },
      { key: "screen_key", label: "屏幕", type: "select", options: SCREEN_KEY_OPTIONS },
      { key: "is_enabled", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
    ],
    fields: [
      {
        key: "screenKey",
        label: "屏幕",
        type: "select",
        required: true,
        defaultValue: "left",
        options: SCREEN_KEY_OPTIONS,
      },
      { key: "moduleKey", label: "模块标识", type: "text", required: true, defaultValue: "" },
      { key: "label", label: "模块名称", type: "text", required: true, defaultValue: "" },
      { key: "isEnabled", label: "启用", type: "checkbox", defaultValue: true },
      { key: "sortOrder", label: "排序", type: "integer", required: true, defaultValue: 0 },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  displayContentConfigs: {
    label: "欢迎展示配置",
    endpoint: "/api/admin/display-content-configs",
    itemLabel: "展示内容配置",
    useModalForm: true,
    columns: [
      { key: "configKey", label: "配置键" },
      { key: "companyName", label: "公司名称" },
      { key: "welcomeMessage", label: "欢迎语" },
      { key: "isActive", label: "启用" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "配置键/公司名/欢迎语" },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      { key: "configKey", label: "配置键", type: "text", required: true, defaultValue: "default" },
      { key: "companyName", label: "公司名称", type: "text", required: true, defaultValue: "" },
      { key: "welcomeMessage", label: "欢迎语", type: "text", required: true, defaultValue: "" },
      { key: "logoUrl", label: "Logo 地址", type: "text", defaultValue: "" },
      { key: "promoImageUrls", label: "宣传图片地址列表", type: "json", defaultValue: [] },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      ...RESERVED_FIELDS,
    ],
  },
};
