import { RESERVED_FIELDS } from "./shared.js";
import {
  ACTIVE_STATUS_OPTIONS,
  ENTITY_TYPE_OPTIONS,
  GANTT_ANCHOR_MODE_OPTIONS,
} from "./options.js";

export const systemResourceDefinitions = {
  codeMappings: {
    label: "编码映射",
    endpoint: "/api/admin/code-mappings",
    itemLabel: "编码映射",
    useModalForm: true,
    columns: [
      { key: "entityType", label: "对象类型" },
      { key: "sourceSystem", label: "来源系统" },
      { key: "internalCode", label: "内部编码" },
      { key: "externalCode", label: "外部编码" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "来源系统/内外编码/备注" },
      { key: "entity_type", label: "对象类型", type: "select", options: ENTITY_TYPE_OPTIONS },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
      { key: "created_at_start", label: "创建开始", type: "date" },
      { key: "created_at_end", label: "创建结束", type: "date" },
    ],
    fields: [
      {
        key: "entityType",
        label: "对象类型",
        type: "select",
        required: true,
        defaultValue: "device",
        options: ENTITY_TYPE_OPTIONS,
      },
      { key: "sourceSystem", label: "来源系统", type: "text", required: true, defaultValue: "" },
      { key: "internalCode", label: "内部编码", type: "text", required: true, defaultValue: "" },
      { key: "externalCode", label: "外部编码", type: "text", required: true, defaultValue: "" },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      ...RESERVED_FIELDS,
    ],
  },
  runtimeParameterConfigs: {
    label: "运行参数配置",
    endpoint: "/api/admin/runtime-parameter-configs",
    itemLabel: "运行参数",
    useModalForm: true,
    bulkApplyToolbar: {
      apiPath: "bulk-runtime-fields",
      fields: [
        {
          key: "singleDayEffectiveWorkHours",
          label: "日有效工时",
          kind: "decimal",
          defaultInput: "16.00",
          min: 0.01,
          max: 24,
          step: "0.01",
        },
        {
          key: "ganttWindowDays",
          label: "甘特窗口天数",
          kind: "integer",
          defaultInput: "30",
          min: 1,
          max: 36500,
          step: "1",
        },
      ],
      successMessage: (count) => `已批量更新 ${count} 条运行参数配置的日有效工时与甘特窗口天数。`,
      errorFallback: "批量设置失败，请稍后重试。",
    },
    columns: [
      { key: "configKey", label: "配置键" },
      { key: "singleDayEffectiveWorkHours", label: "日有效工时" },
      { key: "defaultStandardCapacityPerHour", label: "标准产能/小时" },
      { key: "ganttWindowDays", label: "甘特窗口天数" },
      { key: "ganttAnchorMode", label: "甘特图开始时间" },
    ],
    queryFields: [
      { key: "keyword", label: "关键字", type: "text", placeholder: "配置键/备注" },
      { key: "is_active", label: "启用状态", type: "select", options: ACTIVE_STATUS_OPTIONS },
    ],
    fields: [
      { key: "configKey", label: "配置键", type: "text", required: true, defaultValue: "default" },
      { key: "singleDayEffectiveWorkHours", label: "单日有效工作时长", type: "decimal", required: true, defaultValue: "16.00" },
      { key: "defaultStandardCapacityPerHour", label: "默认标准产能/小时", type: "decimal", required: true, defaultValue: "0.00" },
      { key: "delayWarningBufferHours", label: "延期预警缓冲小时", type: "decimal", required: true, defaultValue: "0.00" },
      { key: "ganttWindowDays", label: "甘特窗口天数", type: "integer", required: true, defaultValue: 30 },
      {
        key: "ganttAnchorMode",
        label: "甘特图开始时间",
        type: "select",
        options: GANTT_ANCHOR_MODE_OPTIONS,
        defaultValue: "earliest_order",
      },
      { key: "autoScrollEnabled", label: "启用自动滚动", type: "checkbox", defaultValue: true },
      { key: "autoScrollRowsThreshold", label: "自动滚动行数阈值", type: "integer", required: true, defaultValue: 10 },
      { key: "recentCapacityWindowHours", label: "最近产能窗口小时", type: "integer", required: true, defaultValue: 2 },
      { key: "productionTrendWindowHours", label: "产量趋势窗口小时", type: "integer", required: true, defaultValue: 8 },
      { key: "notes", label: "备注", type: "textarea", defaultValue: "" },
      { key: "isActive", label: "启用", type: "checkbox", defaultValue: true },
      ...RESERVED_FIELDS,
    ],
  },
operationLogs: {
    label: "操作日志",
    endpoint: "/api/admin/operation-logs",
    itemLabel: "日志",
    readOnly: true,
    columns: [
      { key: "createdAt", label: "时间", cellFormat: "cstDateTime" },
      { key: "actorUsername", label: "管理员" },
      { key: "action", label: "动作" },
      { key: "targetType", label: "对象类型" },
      { key: "targetLabel", label: "对象" },
    ],
    fields: [],
  },
};
